// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ToDo_Data
{
    [Table("ToDoItem")]
    public partial class ToDoItem
    {
        [Key]
        [Column("ToDoItemID")]
        public int ToDoItemId { get; set; }
        [Column("CategoryID")]
        public int CategoryId { get; set; }
        [Column("ToDoItem")]
        [StringLength(200)]
        [Unicode(false)]
        public string ToDoItem1 { get; set; }
        [Column(TypeName = "date")]
        public DateTime? DueDate { get; set; }
        [Column("UserID")]
        public int UserId { get; set; }
        [Column(TypeName = "date")]
        public DateTime? DateCompleted { get; set; }
    }
}